before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- format_overrides:
    - goos: windows
      format: zip
  files:
  - src: .go-status-gif
  - src: README*
    dst: docs
  - src: LICENSE*
    dst: docs
  - src: CHANGELOG*
    dst: docs
release:
  github:
    owner: asphaltbuffet
    name: go-status-gif
  prerelease: auto
announce:
  skip: 'true'